puts'Hello, World'
puts'BI = ビジネスインテリジェンス'
puts'Hello,Hello'
puts'Javaカリキュラム'
puts'Java'
puts'スッキリわかるJava入門/P136'
puts'スッキリわかるJava入門/P186'
puts'スッキリわかるJava入門/P210'
puts'スッキリわかるJava入門/P297'
puts'スッキリわかるJava入門/P222'
